# Generated by Django 4.1.1 on 2022-09-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice", name="votes", field=models.IntegerField(default=0),
        ),
    ]
